services:
  backend:
    image: ghcr.io/chevshan/cover_letter_project/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - shared_uploads:/app/uploads


  frontend:
    image: ghcr.io/chevshan/cover_letter_project/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - shared_uploads:/app/uploads

volumes:
  shared_uploads:
