name: Deploy on push to master

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Create .env file
        run: |
          echo "COVER_LETTER_API_URL=${{ secrets.COVER_LETTER_API_URL }}" > .env
          echo "LLAMA_API_KEY=${{ secrets.LLAMA_API_KEY }}" >> .env
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env

      - name: Start Docker Compose services
        run: |
          docker compose up --build -d

      - name: Check frontend is responding
        run: timeout 30 sh -c 'until curl -s http://localhost:8501/; do sleep 2; done'
        
      - name: Check backend is responding
        run: timeout 30 sh -c 'until curl -s http://localhost:8000/health; do sleep 2; done'

      - name: Shutdown services after test
        if: always()
        run: |
          docker compose down --remove-orphans
  
  push-to-ghcr:
    needs: build-and-run
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
            ghcr.io/${{ github.repository }}/backend:latest
          

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
            ghcr.io/${{ github.repository }}/frontend:latest
